### ISSUE TITLE
程序运行有格式报错

### ISSUE THREAD

**Issue by Auroar** [bddjr/ddns-py-huawei#1]
程序234行和215行好像格式有问题, 运行的时候报错
215行 logger(f'【错误】该程序不支持{config['type']}类型记录！请修改type')
这行得改成logger(f"【错误】该程序不支持{config['type']}类型记录！请修改type")
234行改成mode = input("选择操作模式" + '\n'.join(modelist) + "请输入编号：")

**Comment by bddjr** [comment]
你用哪个版本的python运行导致的

**Comment by Auroar** [comment]
> 你用哪个版本的python运行导致的

3.10.12

**Comment by bddjr** [comment]
我记得我用3.10.6没问题，现在用3.12.2也没问题

**Comment by Auroar** [comment]
> 我记得我用3.10.6没问题，现在用3.12.2也没问题

我是直接在Ubantu里面克隆了运行的, 我看最新的代码215行内部有一个嵌套的单引号，但整个字符串又是用单引号定义的, 这里应该是有错误的, 可能是环境问题?

**Comment by bddjr** [comment]
看看报错内容

**Comment by Auroar** [comment]
> 看看报错内容

root@hcss-ecs-55ad:~/test# git clone https://github.com/bddjr/ddns-py-huawei.git
Cloning into 'ddns-py-huawei'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 45 (delta 21), reused 36 (delta 12), pack-reused 0 (from 0)
Receiving objects: 100% (45/45), 149.59 KiB | 524.00 KiB/s, done.
Resolving deltas: 100% (21/21), done.
root@hcss-ecs-55ad:~/test# ls
ddns-py-huawei
root@hcss-ecs-55ad:~/test# cd ddns-py-huawei/
root@hcss-ecs-55ad:~/test/ddns-py-huawei# python3 ddns.py 
  File "/root/test/ddns-py-huawei/ddns.py", line 215
    logger(f'【错误】该程序不支持{config['type']}类型记录！请修改type')
                                                    ^^^^
SyntaxError: f-string: unmatched '['

**Comment by bddjr** [comment]
我这的Ubuntu修复pip3之后就能运行了，没遇到这个问题，版本3.12.3
